name: nextjs
description: App Description
ignoreFiles: .git .next node_modules yarn.lock package-lock.json
modules:
  - name: template
    language: nodejs22.x
    web: nextjs
    description: Module description
    functions:
      - name: entry
        description: the entry point for the function